permalink: /:year/:month/:day/:title.html
markdown: kramdown
# markdown: redcarpet # redcarpet is no longer supported in Github Pages
highlighter: rouge # pygments currently not supported in Github Pages

kramdown:
  input: GFM

# 作者信息
author: 
  name: ferdi
  email: ferdian.adi@gmail.com
  link: ferdianap.github.io/blog
  twitter: https://twitter.com/itsferdee
  github: https://github.com/ferdianap

# 站点信息
title: Ferdi's Blog 
description: My Mind palace where we together index every node of wisdom's tree
url: https://ferdianap.github.io/blog
baseurl: /blog
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://cdn.rawgit.com/ferdianap/ferdianap.github.io/gh-pages/blog/_docs/avatar.png
favicon: https://cdn.rawgit.com/ferdianap/ferdianap.github.io/gh-pages/blog/_docs/favicon.ico

# google analytics 设置
ga:
  id: UA-39316813-2
  url: auto

# disqus 设置
disqus:
  shortname: ferdianap-github-io-blog