permalink: /:year/:month/:day/:title.html
markdown: kramdown
markdown: redcarpet
highlighter: pygments

kramdown:
  input: GFM

# 作者信息
author: 
  name: ferdi
  email: ferdian.adi@gmail.com
  link: ferdianap.github.io/blog
  twitter: https://twitter.com/itsferdee
  github: https://github.com/ferdianap

# 站点信息
title: Ferdi's Blog 
description: My Mind palace where we together index every node of wisdom's tree
url: https://ferdianap.github.io/blog
baseurl: /blog
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://ferdianap.github.io/images/pp%20150.jpg
favicon: https://ferdianap.github.io/images/favicon.ico

# google analytics 设置
ga:
  id: UA-39316813-2
  url: auto

# disqus 设置
disqus:
  shortname: ferdianap-github-io-blog